### PR TITLE
Bug issue 113

### LINKED ISSUE #113: Status endpoint returns a 401
I think when the middle was added it broke the /status endpoint. We need to exclude getStatus from any auth checks.

### PR DESCRIPTION
**Pull request by jbowen93**
Resolves #113

### CODE REVIEW

**Comment by AdamMagaluk** [comment]
Was this test passing before? https://github.com/30x/enrober/blob/f4316277834dfa232098ceec6f15ad3e5e60f0c7/pkg/server/server_test.go#L19-L28

**Comment by jbowen93** [comment]
If you run that test against a local minikube cluster with `enrober` running in local dev mode it would pass previously since the admin middleware is only enabled in production deployments.

**Comment by AdamMagaluk** [comment]
Ah i see. But now we are always enabling admin middleware

**Comment by jbowen93** [comment]
No it's still only enabled in prod. There's just the additional layer of not failing on the status endpoint. 
https://github.com/30x/enrober/blob/f4316277834dfa232098ceec6f15ad3e5e60f0c7/pkg/server/server.go#L137

**Pull request merged**
